### PR TITLE
fix(moq-relay): judge credential expiry against the deadline, not a span

### PR DESCRIPTION
**Pull request by kixelated**
Completes [quest/m0/auth-expiry-test-clock.md](https://github.com/moq-dev/moq/blob/dev/quest/m0/auth-expiry-test-clock.md), deleted here.

## Problem

`expired_resolves_at_credential_expiry` ran on Tokio's paused clock but built its
deadline from the wall clock, then asserted a span against the paused one:

```rust
#[tokio::test(start_paused = true)]
token.expires = Some(SystemTime::now() + Duration::from_millis(100));  // read 1
let start = tokio::time::Instant::now();
... auth.expired(&token).await ...
assert!(start.elapsed() >= Duration::from_millis(100), "resolved before expiry");
```

`elapsed()` reads `SystemTime::now()` again when the future is first polled, so the
sleep it arms is only the span still **remaining**:

```rust
let remaining = bound.duration_since(std::time::SystemTime::now()).unwrap_or_default();
tokio::time::sleep(remaining).await
```

Any real time between the two reads shortens that sleep by exactly that much, and a
paused clock advances by only the shortened sleep. So `start.elapsed()` came back
under 100ms and the test failed with "resolved before expiry" whenever the workspace
was loaded enough to burn real milliseconds during setup. #3446 hit it.

The failure is in the assertion, not in `elapsed()`: on a live clock the sleep still
ends at the bound.

## Fix

Judge the wait against the deadline itself, which is the one reference both reads
share, and run on the real clock so the sleep and the assertion agree:

```rust
#[tokio::test]
let bound = std::time::SystemTime::now() + Duration::from_millis(100);
token.expires = Some(bound);
tokio::time::sleep(Duration::from_millis(50)).await;   // the regression
... auth.expired(&token).await ...
assert!(std::time::SystemTime::now() >= bound, "resolved before expiry");
```

This is deterministic rather than merely wider: `sleep(remaining)` on a live clock
never returns early, so the wait always ends at or after `bound` no matter how much
real time preceded it. The 50ms sleep is the deterministic regression the quest asked
for - it supplies the wall time a loaded machine used to supply by luck, and reverting
the assertion fails the test 100% of the time rather than intermittently.

Coverage is preserved on both sides: `SystemTime::now() >= bound` proves a credential
does not expire early, and the surviving 5s `timeout` proves it does not stay
authorized past its deadline. No timeout was widened and no retry was added.

## Public API and wire impact

None. Test-only change plus the quest file deletion.

(written by claude-opus-5)

### CODE REVIEW

File: rs/moq-relay/src/auth.rs [hunk 1]
```diff
@@ -5904,18 +5904,28 @@ api = "https://api.example.com/access"
...
 	async fn expired_resolves_at_credential_expiry() {
 		let auth = Auth::default();
 		let mut token = AuthToken::unrestricted(Path::new("").to_owned());
-		token.expires = Some(std::time::SystemTime::now() + Duration::from_millis(100));
+		let bound = std::time::SystemTime::now() + Duration::from_millis(100);
+		token.expires = Some(bound);
+
+		// Real time between building the bound and waiting on it, which is what a
+		// loaded test machine supplies on its own.
+		tokio::time::sleep(Duration::from_millis(50)).await;
```
[the remark this answers is not in the document]
Comment (kixelated) [reply rs/moq-relay/src/auth.rs:5922]: The clock straddle is real, but it lives in `elapsed()` itself, not in the test: it converts a wall-clock bound to a duration and sleeps that on the monotonic clock. Any assertion that a credential did not expire *early* has to compare those same two clocks, because that pairing is exactly what the function promises. Moving the comparison does not remove it.

Both alternatives were tried and are worse:

- **Paused clock, assert the computed remaining.** The impl reads `SystemTime` after the test does, so its remaining is always `<=` the test's. That makes the only deterministic assertion an upper bound (`slept <= remaining`), which proves the sleep does not overshoot but says nothing about resolving early - the half this regression exists to cover.
- **Race a shorter monotonic timeout** (`timeout(200ms, expired)` must not resolve). Pure monotonic, no wall read, but the probe window has to be shorter than whatever is left of the bound, and incidental load shortens that. That reintroduces the exact load sensitivity the quest asked to remove.

Anchoring to the deadline is what makes the test load-independent, and load is what actually broke it in #3446. The residual exposure is a backward wall-clock *step* landing inside a ~150ms window; NTP slews rather than steps on a running host, so this is a different and far smaller risk class than the one being fixed, and it is not a function of test-machine load.

An injected clock would close it, but only by adding a seam to `auth.rs` for a test - against this repo's rule to keep things private until a consumer needs them. Not worth the production surface for this.

(written by claude-opus-5)
